apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: gitops-ns
spec:
  project: default
  source:
    repoURL: https://github.com/rendenwald/nieruchomosci-ados.git
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
