"""Create core tables: properties (partitioned), agencies, scraper_runs.

Revision ID: 0001
Revises:
Create Date: 2026-06-20
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  # Required for Geometry type
import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Enable PostGIS extension
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ------------------------------------------------------------------ #
    # properties — LIST partitioned by portal_source                      #
    # ------------------------------------------------------------------ #
    op.execute("""
        CREATE TABLE properties (
            id              INTEGER     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            portal_source   VARCHAR(50) NOT NULL,
            source_id       VARCHAR(255) NOT NULL,
            source_url      TEXT,

            -- Content
            title           VARCHAR(500),
            description     TEXT,
            property_type   VARCHAR(50),
            auction_type    VARCHAR(20),
            market_type     VARCHAR(20),
            offered_by      VARCHAR(20),

            -- Promotion
            is_promoted             BOOLEAN NOT NULL DEFAULT FALSE,
            promotion_expires_at    TIMESTAMP WITH TIME ZONE,

            -- Pricing
            price           INTEGER,
            price_currency  VARCHAR(3) NOT NULL DEFAULT 'PLN',
            price_per_m2    INTEGER,
            rent            INTEGER,

            -- Dimensions
            area            FLOAT,
            plot_area       FLOAT,
            rooms           VARCHAR(50),
            floor           VARCHAR(50),
            floors_total    INTEGER,
            year_built      INTEGER,
            condition       VARCHAR(50),
            heating         VARCHAR(100),
            extras          JSONB,

            -- Location
            province        VARCHAR(100),
            city            VARCHAR(100),
            district        VARCHAR(100),
            street          VARCHAR(255),
            latitude        FLOAT,
            longitude       FLOAT,
            location        GEOMETRY(Point, 4326),

            -- Agency
            agency_name         VARCHAR(255),
            agency_source_id    VARCHAR(255),

            -- Media
            photos          JSONB,
            localization    JSONB,
            building        JSONB,

            -- Deduplication
            duplicate_group_id  UUID,
            is_canonical        BOOLEAN NOT NULL DEFAULT TRUE,

            -- Timestamps
            scraped_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
            last_seen_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
            is_active       BOOLEAN NOT NULL DEFAULT TRUE,
            source_created_at TIMESTAMP WITH TIME ZONE,

            PRIMARY KEY (id, portal_source)
        ) PARTITION BY LIST (portal_source)
    """)

    # Create partitions for known portal sources.
    # To add a new portal source after deployment:
    #   1. CREATE TABLE properties_<new> PARTITION OF properties
    #      FOR VALUES IN ('<new-portal>');
    #   2. The 'properties_other' DEFAULT partition catches any sources
    #      not yet explicitly partitioned. Move data from DEFAULT to a
    #      dedicated partition via ALTER TABLE ... ATTACH PARTITION.
    # Example:
    #   CREATE TABLE properties_morizon PARTITION OF properties
    #   FOR VALUES IN ('morizon');
    op.execute("CREATE TABLE properties_otodom PARTITION OF properties FOR VALUES IN ('otodom')")
    op.execute("CREATE TABLE properties_gratka PARTITION OF properties FOR VALUES IN ('gratka')")
    op.execute(
        "CREATE TABLE properties_nieruchomosci_online PARTITION OF properties FOR VALUES IN ('nieruchomosci-online')"
    )
    op.execute("CREATE TABLE properties_other PARTITION OF properties DEFAULT")

    # Unique constraint on (portal_source, source_id) for upsert
    op.create_unique_constraint(
        "uq_properties_source",
        "properties",
        ["portal_source", "source_id"],
    )

    # Search index
    op.create_index(
        "idx_properties_search",
        "properties",
        ["city", "property_type", "auction_type", "price"],
        postgresql_where=sa.text("is_canonical = TRUE AND is_active = TRUE"),
    )

    # PostGIS spatial index (GIST on geography column)
    op.create_index(
        "idx_properties_location",
        "properties",
        ["location"],
        postgresql_using="gist",
        postgresql_where=sa.text("is_canonical = TRUE"),
    )

    # ------------------------------------------------------------------ #
    # agencies                                                            #
    # ------------------------------------------------------------------ #
    op.create_table(
        "agencies",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("portal_source", sa.String(50), nullable=False),
        sa.Column("source_id", sa.String(255), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("nip", sa.String(20), nullable=True),
        sa.Column("street", sa.String(255), nullable=True),
        sa.Column("city", sa.String(100), nullable=True),
        sa.Column("province", sa.String(100), nullable=True),
        sa.Column("postal_code", sa.String(20), nullable=True),
        sa.Column("subscription_tier", sa.String(50), nullable=True),
        sa.Column("subscription_expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_unique_constraint("uq_agencies_source", "agencies", ["portal_source", "source_id"])

    # ------------------------------------------------------------------ #
    # scraper_runs                                                        #
    # ------------------------------------------------------------------ #
    op.create_table(
        "scraper_runs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("portal_source", sa.String(50), nullable=False),
        sa.Column("scraper_id", sa.String(255), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("listings_scraped", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("listings_new", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("listings_updated", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("errors_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="running"),
        sa.Column("error_message", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("scraper_runs")
    op.drop_table("agencies")
    op.execute("DROP TABLE IF EXISTS properties_otodom")
    op.execute("DROP TABLE IF EXISTS properties_gratka")
    op.execute("DROP TABLE IF EXISTS properties_nieruchomosci_online")
    op.execute("DROP TABLE IF EXISTS properties_other")
    op.execute("DROP TABLE IF EXISTS properties CASCADE")
    op.execute("DROP EXTENSION IF EXISTS postgis")
